/**
 * Shared type definitions for VisionDoc AI.
 *
 * OCR and the structured AI explanation are now implemented on the
 * backend, so `ocr_text` and `ai_explanation` are required fields below.
 *
 * `annotated_image` and `medical_report` are NOT implemented yet, so they
 * stay OPTIONAL — the UI reads them defensively today (they'll be
 * `undefined`), and will automatically start rendering real data the
 * moment the backend adds them, with no type or component changes needed.
 */

/** A single bounding-box detection returned by the YOLO model. */
export interface Detection {
  /** Model confidence score between 0 and 1. */
  confidence: number;
  /** Bounding box as [x1, y1, x2, y2] in original image pixel coordinates. */
  bbox: [number, number, number, number];
  /** Optional class label — not returned by the backend yet, but future-ready. */
  label?: string;
}

/** Structured, patient-friendly explanation generated by the Gemini LLM. */
export interface AiExplanation {
  summary: string;
  findings: string[];
  limitations: string;
  recommendation: string;
}

/** The full prediction response from POST /predict/. */
export interface PredictionResponse {
  total_detections: number;
  detections: Detection[];
  ocr_text: string;
  ai_explanation: AiExplanation;

  // ---- Future / not-yet-implemented backend fields ----
  /** Base64 or URL of a server-annotated image, once/if the backend renders it. */
  annotated_image?: string;
  /** Structured medical report text, if the backend adds this later. */
  medical_report?: string;
}

export type BackendStatus = "checking" | "online" | "offline";

export type AnalysisStatus = "idle" | "uploading" | "analyzing" | "success" | "error";

export interface AppError {
  title: string;
  message: string;
  kind: "network" | "validation" | "backend" | "empty" | "unknown";
}

export interface HistoryItem {
  id: string;
  fileName: string;
  date: string;
  totalDetections: number;
  status: "completed" | "failed";
}
